server:
  port: ${SERVER_PORT:8081}

spring:
  r2dbc:
    url: r2dbc:h2:mem:///~/db/testdb
    username: sa
    password:
  flyway:
    url: jdbc:h2:mem:~/db/testdb;DB_CLOSE_DELAY=-1
    user: sa
    password:

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    org.zalando.logbook: TRACE

integration:
  person:
    url: ${PERSON_URL:http://localhost:8080}
    path-id: ${PERSON_PATH_ID:/person/{id}}
    connect-timeout: ${PERSON_CONNECTION_TIMEOUT:5000}
    read-timeout: ${PERSON_READ_TIMEOUT:5000}